### ISSUE TITLE
GOST4401_81.cpp

### ISSUE THREAD

**Issue by nomad605dis** [realspinner/GOST4401_81#1]
Hi!
It seems to me in file GOST4401_81.cpp at line 63:
for (idx = 1; idx < GOST4401_LUT_RECORDS - 1; idx++) {
necessary: 
for (idx = 0; idx < GOST4401_LUT_RECORDS - 1; idx++) {

?
This mistake in cycle leads to an incorrect result of calculating atmospheric pressure on height down 20000 meters.

The same mistake has in function GOST4401_getTemperature

Please check it

**Comment by realspinner** [comment]
Hi,

You're absolutely right. I have fixed it. Thank you.
